# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from fileinput import filename
from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import *
from tkinter import filedialog
from tkvideo import tkvideo



OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./input_assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def vid():
    window.destroy()
    import test


def browseFiles():
    filename = filedialog.askopenfilename(initialdir = "/",
                                          title = "Select a File",
                                          filetypes = (("Text files",
                                                        "*.txt*"),
                                                       ("all files",
                                                        "*.*")))
      
    # Change label contents
    label_file_explorer.configure(text="File Opened: "+filename)
    print(filename)
    vid()


 
      
      
window = Tk()

window.geometry("1440x689")
window.configure(bg = "#FFFFFF")

# set window title
# window.title('Video Player')
# # create label
# video_label = Label(window)
# video_label.pack()
# # read video to display on label
# player = tkvideo(filename, video_label,
#                  loop = 1, size = (700, 500))
# player.play()
# window.mainloop()


label_file_explorer = Label(window,
                            text = "File Explorer using Tkinter",
                            width = 100, height = 4,
                            fg = "blue")

canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 689,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    720.0,
    344.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    195.0,
    75.0,
    image=image_image_2
)

canvas.create_rectangle(
    66.0,
    63.0,
    92.0,
    67.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    66.0,
    70.0,
    92.0,
    74.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    66.0,
    77.0,
    92.0,
    81.0,
    fill="#FFFFFF",
    outline="")

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    1262.0,
    67.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    1325.0,
    65.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    441.0,
    391.0,
    image=image_image_5
)
#hena 

canvas.create_rectangle(
    824.0,
    453.0,
    1267.0,
    510.0,
    fill="#FFFFFF",
    outline="")
#Upload Button
button_image_1 = PhotoImage(
    file=relative_to_assets("image_6.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    text="button_1 clicked",
    command=browseFiles,
    relief="flat"
)
button_1.place(
    x=1177.0,
    y=460.0,
    width=88.0,
    height=50.0
)

window.resizable(False, False)
window.mainloop()