
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from cgitb import text
from email import message
import tkinter.font as font
from regex import E, P
import pyrebase
import json
from tkinter import messagebox
from tkinter.ttk import *
from urllib3.exceptions import HTTPError as BaseHTTPError
from pathlib import Path
from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from turtle import bgcolor, color


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./signup_assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)



def SignUp():
    config = {'apiKey': "AIzaSyD3SaqfyUcu1Xnjkeaqw3ILpn_w4v5s4Fo",
    'authDomain': "pruney-4e073.firebaseapp.com",
    'databaseURL':"https://pruney-4e073.firebaseapp.com",
    'projectId': "pruney-4e073",
    'storageBucket': "pruney-4e073.appspot.com",
    'messagingSenderId': "969307424804",
    'appId': "1:969307424804:web:f6706080c47108567430b1",
    'measurementId': "G-FQRT3VDG5B"}
    global my_text
    global my_text_2

    firebase = pyrebase.initialize_app(config)
    auth = firebase.auth()

    email = entry_1.get()
    password = entry_2.get()

    if not email:
         my_text = "Please Enter An Email"
         EmailErr()
    elif not password:
        my_text = ""
        EmailErr()
        my_text_2 = "Please Enter A Password"
        PassErr()
    else:
        try:
            user = auth.create_user_with_email_and_password(email, password)
            print("Account Created")
            on_Click()
            HomePage()
            window.destroy()
        
        except Exception as e:
        #    print(e)
           error_json = e.args[1]
           error = json.loads(error_json)['error']['message']
           Err=""
           if error == "INVALID_EMAIL":
            # Err="Email invalid"
            my_text = "Invalid Email Format (@example.com)"
            EmailErr()
           elif error == "EMAIL_EXISTS":
            # Err="Email already exists" 
            my_text = "Email already exists"
            EmailErr()
           elif error == "WEAK_PASSWORD : Password should be at least 6 characters":
            # Err="Password should be at least 6 characters"
            my_text = ""
            EmailErr()
            my_text_2 = "Password should be at least 6 characters"
            PassErr()

           if Err!="":
            messagebox.showerror('Sign Up Error', Err)

def HomePage():
    window.destroy()
    import Home

def SignInPage():
    window.destroy()
    import signin

global my_text
global my_text_2
def EmailErr():
    global my_text
    my_label.config(text = my_text)

def PassErr():
    global my_text_2
    my_label_2.config(text = my_text_2)

def on_Click():
	messagebox.showinfo("Hello", "Account Created Successfully")

window = Tk()
window.geometry("1440x689")
window.configure(bg = "#FFFFFF")
myFont = font.Font(family='Roboto Thin', size=15)
myFont_2 = font.Font(family='Roboto Thin', size=9)
canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 689,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    1440.0,
    689.0,
    fill="#B44E9D",
    outline="")

canvas.create_rectangle(
    0.0,
    0.0,
    552.0,
    820.0,
    fill="#F7FFFF",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    
    fg="#313072",
    bg="#B44E9D",
    borderwidth=0,
    highlightthickness=0,
    relief="flat",
    command=HomePage,
    activebackground='#B44E9D'
    
)
button_1.place(
    x=569.0,
    y=61.0,
    width=200.0,
    height=50.0
)

# button_image_2 = PhotoImage(
#     file=relative_to_assets("button_2.png"))
button_2 = Button(
    # image=button_image_2,
    text="Sign In",
    bg="#B44E9D",
    fg='#000000',
    borderwidth=0,
    highlightthickness=0,
    command=SignInPage,
    relief="flat"
)
button_2.place(
    x=1276.0,
    y=65.0,
    width=65.0,
    height=31.0
)
button_2['font'] = myFont
canvas.create_text(
    122.0,
    94.0,
    anchor="nw",
    text="Sign Up",
    fill="#000000",
    font=("Roboto Bold", 48 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    136.0,
    238,
    image=image_image_1
)

canvas.create_text(
    160.0,
    230,
    anchor="nw",
    text="Email",
    fill="#000000",
    font=("Roboto Thin", 14 * -1)
)


entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    285.0,
    280.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#F9F8F8",
    highlightthickness=0
)
entry_1.place(
    x=114.0,
    y=256.0,
    width=342.0,
    height=47.0
)
my_label = Label( text = "",
bg="#FFFFFF",
fg="red")

my_label.place(
     x=114.0,
     y=310.0
   
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    136.0,
    350.0,
    image=image_image_2
)


canvas.create_text(
    160.0,
    340.0,
    anchor="nw",
    text="Password",
    fill="#000000",
    font=("Roboto Thin", 14 * -1)
)
entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_1.png"))

entry_bg_2 = canvas.create_image(
    285.0,
    400.0,
    image=entry_image_2
)

e1_str=StringVar()
entry_2 = Entry(
    bd=0,
    bg="#F9F8F8",
    highlightthickness=0,
    show='*',
    textvariable=e1_str
)

entry_2.place(
    x=114.0,
    y=367.0,
    width=342.0,
    height=47.0
)

c_v1=IntVar(value=0)

def my_show():
    
    if(c_v1.get()==1):
        entry_2.config(show='')
    else:
        entry_2.config(show='*')

c1 = Checkbutton(text='Show Password',variable=c_v1,
	onvalue=1,offvalue=0,command=my_show,bg = "#FFFFFF",)

c1.place(
    x=70.0,
    y=450.0,
    width=200.0,
    height=45.0
)

c1['font'] = myFont_2

my_label_2 = Label( text = "",
bg="#FFFFFF",
fg="red")

my_label_2.place(
     x=114.0,
     y=430.0 
)

button_image_1 = PhotoImage(
    file=relative_to_assets("SignUp.png"))
button_1 = Button(
    image=button_image_1,
    bg = "#FFFFFF",
    fg='#B44E9D',
    borderwidth=0,
    highlightthickness=0,
    command=SignUp,
    relief="flat",
    
)
button_1.place(
    x=150.0,
    y=500.0,
    width=257.0,
    height=100.0
)
button_1['font'] = myFont
# entry_image_3 = PhotoImage(
#     file=relative_to_assets("entry_3.png"))
# entry_bg_3 = canvas.create_image(
#     285.0,
#     430.5,
#     image=entry_image_3
# )
# entry_3 = Entry(
#     bd=0,
#     bg="#F9F8F8",
#     highlightthickness=0
# )
# entry_3.place(
#     x=114.0,
#     y=406.0,
#     width=342.0,
#     height=47.0
# )

# entry_image_4 = PhotoImage(
#     file=relative_to_assets("entry_4.png"))
# entry_bg_4 = canvas.create_image(
#     285.0,
#     513.5,
#     image=entry_image_4
# )
# # entry_4 = Entry(
#     bd=0,
#     bg="#F9F8F8",
#     highlightthickness=0
# )
# entry_4.place(
#     x=114.0,
#     y=489.0,
#     width=342.0,
#     height=47.0
# )

# entry_image_5 = PhotoImage(
#     file=relative_to_assets("entry_5.png"))
# entry_bg_5 = canvas.create_image(
#     285.0,
#     600.5,
#     image=entry_image_5
# )
# entry_5 = Entry(
#     bd=0,
#     bg="#F9F8F8",
#     highlightthickness=0
# )
# entry_5.place(
#     x=114.0,
#     y=576.0,
#     width=342.0,
#     height=47.0
# )

# canvas.create_text(
#     160.0,
#     508.0,
#     anchor="nw",
#     text="Email",
#     fill="#868686",
#     font=("Roboto Thin", 14 * -1)
# )

# canvas.create_text(
#     167.0,
#     264.0,
#     anchor="nw",
#     text="First Name",
#     fill="#868686",
#     font=("Roboto Thin", 14 * -1)
# )

# canvas.create_text(
#     161.0,
#     344.0,
#     anchor="nw",
#     text="Last Name",
#     fill="#868686",
#     font=("Roboto Thin", 14 * -1)
# )

# canvas.create_text(
#     160.0,
#     420.0,
#     anchor="nw",
#     text="Mobile Number",
#     fill="#868686",
#     font=("Roboto Thin", 14 * -1)
# )



# canvas.create_text(
#     402.0,
#     590.0,
#     anchor="nw",
#     text="Show",
#     fill="#10105E",
#     font=("Roboto", 14 * -1)
# )


# canvas.create_rectangle(
#     1283.0,
#     91.0,
#     1329.0,
#     91.0,
#     fill="#000000",
#     outline="")

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    1182.0,
    405.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    824.0,
    622.0,
    image=image_image_4
)

# image_image_5 = PhotoImage(
#     file=relative_to_assets("image_5.png"))
# image_5 = canvas.create_image(
#     137.0,
#     433.0,
#     image=image_image_5
# )

# image_image_6 = PhotoImage(
#     file=relative_to_assets("image_6.png"))
# image_6 = canvas.create_image(
#     137.0,
#     272.0,
#     image=image_image_6
# )

# image_image_7 = PhotoImage(
#     file=relative_to_assets("image_7.png"))
# image_7 = canvas.create_image(
#     137.0,
#     351.0,
#     image=image_image_7
# )
window.resizable(False, False)
window.mainloop()
