
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1440x689")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 689,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    1440.0,
    689.0,
    fill="#6079BD",
    outline="")

canvas.create_rectangle(
    0.0,
    0.0,
    600,
    800,
    fill="#F7FFFF",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    302.0,
    301.0,
    image=image_image_1
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=50,
    highlightthickness=50,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=158.0,
    y=484.0,
    width=113.0,
    height=42.0
)

canvas.create_text(
    158.0,
    543.0,
    anchor="nw",
    text="Don't have an accout?\n",
    fill="#10105E",
    font=("Roboto Thin", 14 * -1)
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button (
    # text="Sign Up",
    # font=("Roboto Medium", 14 * -1),
    image=button_image_2,
    borderwidth=20,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=158.0,
    y=564.0,
    width=49.0,
    height=22.0
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    720.0,
    331.0,
    image=image_image_2
)
window.resizable(False, False)
window.mainloop()
